# Generated by Django 3.0.7 on 2020-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
