# Generated by Django 3.0.7 on 2020-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200713_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='comment_status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
