# Generated by Django 3.0.7 on 2020-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200714_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(default=False, verbose_name='Опубликовать?'),
        ),
    ]
