# Generated by Django 3.0.7 on 2020-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200714_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=True, verbose_name='Можно комментировать?'),
        ),
    ]
