# Generated by Django 3.0.7 on 2020-07-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200714_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
    ]
