# Generated by Django 3.0.7 on 2020-07-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_post_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='public_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parental_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_category_parent_+', to='mainapp.Category', verbose_name='Категория-родитель'),
        ),
    ]
