# Generated by Django 3.0.7 on 2020-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200716_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excert',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
    ]
