# Generated by Django 3.0.7 on 2020-07-17 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200716_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('status', models.BooleanField(default=False, verbose_name='Опубликовать?')),
                ('menu', models.BooleanField(default=False, verbose_name='Выставить в меню?')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Главное фото'),
        ),
    ]
