# Generated by Django 3.0.7 on 2020-07-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_post_liblery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
